
name: "Check if documentation has been updated"

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.md"
      - ".github/workflows/*.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: install tf_docs
        env:
          TERRAFORM_DOCS_VERSION: 0.19.0
        run: |
          mkdir -p bin
          curl -Lo terraform-docs.tar.gz "https://github.com/terraform-docs/terraform-docs/releases/download/v$TERRAFORM_DOCS_VERSION/terraform-docs-v$TERRAFORM_DOCS_VERSION-linux-amd64.tar.gz" \
            && tar -xzf terraform-docs.tar.gz terraform-docs\
            && chmod +x terraform-docs \
            && mv terraform-docs bin/ \
            && rm terraform-docs.tar.gz
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Check if docs have been updated
        run: |
          make docs
          rm -rf bin/terraform-docs
          # Check if there are any files to commit
          if [[ $(git status --porcelain) ]]; then
            # If there are, display the list of files and exit with a non-zero status code
            echo "ðŸ’© The following READMEs need to be rebuilt.  Run `make docs` to rebuild them and commit the changes."
            git status --porcelain
            git status --porcelain | sed -e 's/^M/**Modified**/' -e 's/^A/**Added**/' -e 's/^D/**Deleted**/' >> $GITHUB_STEP_SUMMARY
            echo "Changes found"
            git diff
            exit 1
          fi
