name: "Test modules"

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ca-central-1
  GO_VERSION: 1.21.1
  TERRAFORM_VERSION: 1.7.0
  CONFTEST_VERSION: 0.27.0

permissions:
  contents: read
  id-token: write

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Run conftest
        working-directory: .github/workflows/conftest
        run: ../scripts/run-conftest.sh

  terratest:
    needs: conftest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - resolver_dns
          - S3
          - S3_log_bucket

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: dorny/paths-filter@7267a8516b6f92bdb098633497bad573efdbf271 # v2.12.0
        id: changes
        with:
          filters: |
            module:
              - '${{ matrix.module }}/**/*.tf'
              - '${{ matrix.module }}/test/**'
              - '.github/workflows/terratest.yml'

      - name: Configure AWS credentials using OIDC
        if: steps.changes.outputs.module == 'true'
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::124044056575:role/terraform-modules-test
          role-session-name: TFTest
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Go
        if: steps.changes.outputs.module == 'true'
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Terraform tools
        if: steps.changes.outputs.module == 'true'
        uses: cds-snc/terraform-tools-setup@v1

      - name: Terratest
        if: steps.changes.outputs.module == 'true'
        run: |
          cd ${{ matrix.module }}/test
          go mod tidy
          go test -v -timeout 1h
