name: "Test modules"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.16.6
  TERRAFORM_VERSION: 1.0.3
  CONFTEST_VERSION: 0.27.0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Conftest
        run: |
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" \
            && wget "https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/checksums.txt" \
            && grep 'Linux_x86_64.tar.gz' < checksums.txt | sha256sum --check  --status \
            && tar -zxvf "conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" conftest \
            && mv conftest /usr/local/bin \
            && rm "conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz" checksums.txt
      - name: Run conftest
        working-directory: .github/workflows/conftest
        run: ../scripts/run-conftest.sh

  terratest:
    needs: conftest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - notify_slack
          - rds
          - S3
          - S3_log_bucket
          - user_login_alarm
          - vpc
          - lambda

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
      id: changes
      with:
        filters: |
          module:
            - '${{ matrix.module }}/**/*.tf'
            - '${{ matrix.module }}/test/**'

    - name: Setup Go
      if: steps.changes.outputs.module == 'true'
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Setup Terraform
      if: steps.changes.outputs.module == 'true'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: Terratest
      if: steps.changes.outputs.module == 'true'
      run: |
        cd ${{ matrix.module }}/test
        go mod tidy
        go test -v -timeout 1h